---
title: "Intro MSB104"
format: html
editor: visual
---

```{r}
#| label: setup
library(tidyverse)
library(modelsummary)
library(flextable)
```

```{r}
# A few constants
# Add data from SSB 10209: Persons killed or 
# injured in road traffic accidents, by contents 
# and month and DNV 2016 Figur and 3.2 Unike 
# cruiseskip i norske farvann per måned.

boats <- data.frame(
  "month" = c(1:12), 
  # accidents
  "acc" = c(
    312,    314,    272,    304,    415,    447,    
    418,    442,    432,    395,    291,    332
  ), 
  "boats" = c(
    1,  6,  9,  11, 52, 78, 72, 68, 45, 
    11, 8,  5
  ), 
  "weather" = c(
    4.3,    4.5,    6.5,    10.4,   14.7, 17.3 , 
    19.1 , 18.6 , 15.4 , 11.4 , 7.3 ,   4.8 
  ), 
  "daylight" = c(
    6.5,    9.3,    12, 14.5, 17.3, 19 ,17.5 , 
    15.3 , 12.3 , 10 , 7.3 , 5.5
  )
) 

# Norm data so that all is between 0 and 1
boats <- boats %>% 
  mutate(
    boats_n = (boats - 0) / (80 - 0),
    acc_n = (acc - 250) / (450 - 250)
  )



```

```{r}
#Estimates 
lm.1 = lm(
  formula = 'acc ~ boats' , 
  data = boats
) 
lm.2 = lm(
  formula = 'weather ~  boats', 
  data = boats
) 
lm.3 = lm(
  formula = 'acc ~ boats + weather', 
  data = boats
) 
```

```{r}
plot(
  x = boats$boats,
  y = boats$acc,
)
abline(lm.1)
```

```{r}
modelsummary(
  models = list(
    `Mod 1\nY: accidents` = lm.1,
    `Mod 2\nY: weather` = lm.2,
    `Mod 3\nY: accidents` = lm.3
  ),
  estimate = "estimate",
  # statistic gives t-values
  statistic = "statistic",
  output = "flextable",
  fmt = 3,
  stars = TRUE,
  title = "Model 1-3. T-values in parentheses below estimate."
)   |> 
  autofit() |> 
  theme_booktabs() |> 
  fontsize(size = 11) |> 
  line_spacing(space = 0.2)
```

```{r}
# Viser det samme som ovenfor men har mer "luft". Bruk derfor den ovenfor. 
modelsummary(
  models = list(
    `Mod 1\nY: accidents` = lm.1,
    `Mod 2\nY: weather` = lm.2,
    `Mod 3\nY: accidents` = lm.3
  ),
  estimate = "estimate",
  # statistic gives t-values
  statistic = "statistic",
  output = "flextable",
  fmt = 3,
  stars = TRUE,
  title = "Model 1-3. T-values in parentheses below estimate."
)  
```
